### PR TITLE
feat: add more example

### PR DESCRIPTION
**Pull request by a631807682**
#### What this PR does / why we need it (English/Chinese):

en: Add a more example for servicecomb
zh: 增加`servicecomb`示例

#### Which issue(s) this PR fixes:

https://github.com/cloudwego/hertz/issues/485

### CODE REVIEW

**Comment by welkeyever** [comment]
Covered by #79 ?

**Comment by a631807682** [comment]
> Covered by #79 ?

Doesn't seem to be related to #79,  #79 proposes using sonic optimizations, but servicecomb itself doesn't require serialization, only used in the example.
Of course we can also use sonic in the example, but in general they don't have much relationship.

**Comment by li-jin-gou** [comment]
need to cr

**Comment by li-jin-gou** [comment]
PATl @justlorain @L2ncE

**Review by welkeyever — APPROVED** [review]
LGMT

**Review by justlorain — APPROVED** [review]
LGTM

**Pull request merged**
